# Generated by Django 5.0.7 on 2024-10-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('encargado', models.CharField(max_length=100, verbose_name='Encargado')),
                ('contacto_encargado', models.CharField(max_length=100, verbose_name='Contacto del encargado')),
                ('vertientes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('ubicación', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
                'db_table': 'comunidad',
                'ordering': ['id'],
            },
        ),
    ]
