# Generated by Django 5.0.7 on 2024-10-12 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_vertiente_kit_datos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vertiente',
            name='comunidad',
        ),
        migrations.RemoveField(
            model_name='datos',
            name='kit',
        ),
        migrations.RemoveField(
            model_name='datos',
            name='vertiente',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='vertiente',
        ),
        migrations.DeleteModel(
            name='Comunidad',
        ),
        migrations.DeleteModel(
            name='datos',
        ),
        migrations.DeleteModel(
            name='kit',
        ),
        migrations.DeleteModel(
            name='vertiente',
        ),
    ]
