# Generated by Django 5.0.7 on 2024-10-15 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_vertiente_comunidad_remove_datos_kit_and_more'),
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoreo.comunidad'),
        ),
        migrations.AddField(
            model_name='user',
            name='edad',
            field=models.CharField(choices=[('18-24 años', '18-24 años'), ('25-54 años', '25-54 años'), ('55-64 años', '55-64 años'), ('65 años y más', '65 años y más')], default='No informado', verbose_name='Rango etario'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No informado', 'No informar')], default='No informado', verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(default='Usuario', max_length=20, null=True, verbose_name='Tipo'),
        ),
    ]
