# Generated by Django 5.0.7 on 2024-10-15 23:52

from django.db import migrations

def create_user_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Administrador')
    Group.objects.get_or_create(name='Usuario')

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_user_comunidad_user_edad_user_gender_user_phone_and_more'),
    ]

    operations = [
        migrations.RunPython(create_user_groups),
    ]
